// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

export default ({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'npx tsx ./prisma/seed.ts',
  },
  datasource: {
<<<<<<< feature/authentication-system
    url: process.env.DATABASE_URL,
=======
    url: process.env.DATABASE_URL, //idl why it can't recognize the process variable, does it need to be included in compilation?
>>>>>>> main
  },
});
