// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import {env} from "prisma/config";

export default ({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'npx tsx ./prisma/seed.ts',
  },
  datasource: {
    // https://www.prisma.io/docs/orm/reference/prisma-config-reference#engine
    url: env("DATABASE_URL"), // process.env.DATABASE_URL
  },
});
